language: cpp

os: linux
sudo: false
dist: trusty

env:
  global:
    - DEVKITPRO=/opt/devkitpro    
    - DEVKITARM=/opt/devkitpro/devkitARM
    
cache:
  directories:
    - "$HOME/.local"
    - "$DEVKITPRO"

before_install:
  - curl -L https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -o pacman.deb
  - sudo apt-get install -y p7zip-full

install:
  - sudo dpkg -i pacman.deb
  - sudo dkp-pacman -Sy
  - sudo dkp-pacman -S devkitARM general-tools dstools ndstool libnds libfat-nds grit mmutil --noconfirm
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

script:
  - export COMMIT_TAG="$(git log --format=%h -1)"
  - export COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
  - make
  - mkdir ButtonBoot/
  - cp ButtonBoot.nds ButtonBoot/
  - 7z a ButtonBoot.7z ButtonBoot/
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libstdc++6
    - lftp

after_success:
  - curl -o send.sh https://raw.githubusercontent.com/DS-Homebrew/discord-webhooks/master/send-travis.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  - git config --local user.name "TWLBot"
  - git clone https://$GITHUB_TOKEN@github.com/TWLBot/Builds.git
  - cd Builds/extras
  - cp ../../ButtonBoot.7z ButtonBoot.7z
  - git stage .
  - git commit -m "ButtonBoot | $COMMIT_TAG"
  - git push origin master
  - export CURRENT_DATE=$(date +'%Y%m%d-%H%M%S')
  - git tag v$CURRENT_DATE

after_failure:
  - curl -o send.sh https://raw.githubusercontent.com/DS-Homebrew/discord-webhooks/master/send-travis.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
